on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

name: Create Changelog

jobs:
  build:
    name: Create Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate full changelog
        id: generateChangelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          unreleasedOnly: false

      - name: Commit changelog
        uses: EndBug/add-and-commit@v4
        with:
          add: CHANGELOG.md
          message: 'Updated changelog'
          ref: ${{ github.event.pull_request.head.ref }} # The HEAD branch
          tag: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
