on:
  pull_request:
    types: [closed]
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate recent changelog
        id: recent_changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          sinceTag: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/branches\//}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.recent_changelog.outputs.changelog }}
          draft: false
          prerelease: false
