on:
  pull_request:
    types: [closed]
    branches:
      - main

name: Create Release

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate recent changelog
        id: recent_changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          # unreleasedOnly: true
          unreleased: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions-ecosystem/action-regex-match@v2
        id: get_version
        with:
          text: ${{ github.event.pull_request.head.ref }}
          regex: 'releases?\/(v\d+\.\d+\.\d+)'

      - name: Create Release
        if: ${{ steps.get_version.outputs.match != '' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.group1 }}
          release_name: Release ${{ steps.get_version.outputs.group1 }}
          body: |
            ${{ steps.recent_changelog.outputs.changelog }}
          draft: false
          prerelease: false
