on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate full changelog
        id: generateChangelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md

      - name: Commit changelog and update tag
        uses: EndBug/add-and-commit@v4
        with:
          add: CHANGELOG.md
          message: 'Updated changelog'
          tag: ${{ github.ref }} # Update the tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate recent changelog
        id: recent_changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          onlyLastTag: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.recent_changelog.outputs.changelog }}
          draft: false
          prerelease: false
